/**
 * Created by Davide on 2026-01-28 .
 *
 * @formatter:off
 */

package build_orchestrator;

import dparam.AParams;
import dparam.ParamMono;
import dparam.pvdc.AValueChangeInfo;
import dparam.pvdc.change_loader.AValueChangeTextReader;
import dparam.pvdc.change_loader.EmptyValueChangeTextReader;
import dutil.string.value_parser.BooleanStringParser;
import dutil.string.value_parser.LongStringParser;
import dutil.string.value_parser.NeutralStringParser;
import jakarta.validation.constraints.NotNull;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

import java.io.Serial;
import java.util.List;
import java.util.Map;

import static dfile.file.FileUtilities.SEPARATOR_CHAR;
import static dfile.file.FileUtilities.calcPath;
import static dutil.date.DateTimeUtilities.MS_IN_HOUR;
import static dutil.number.NumberUtilities.L;
import static dutil.number.NumberUtilities.ZERO_l;
import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import static java.util.Arrays.asList;
import static org.apache.commons.lang3.StringUtils.EMPTY;
import static org.apache.commons.lang3.StringUtils.defaultIfBlank;
import static org.apache.commons.lang3.StringUtils.isNotBlank;

/**
 * Class containing the fields that represent the user-controlled parameters (AKA "inputs") of a {@link
 * BuildOrchestrator} executable instance.<br><br>
 * The {@link AValueChangeInfo#marker Value Change Marker}s are of unspecified type because {@link BuildOrchestrator}
 * doesn't use the PVDC functionality (<b>PVDC</b> = <i>Parameter Value Dynamic Change</i>).
 */
@ToString(callSuper = true)
public class BuildOrchestratorParams extends AParams<Object> {
	
	
	@Serial
	private static final long serialVersionUID = -4623955895467891834L;
	
	/**
	 * Default for optional param {@link #commandTimeoutMs}, 1 h (3,600,000 ms).
	 */
	private static final long DEFAULT_COMMAND_TIMEOUT_MS = MS_IN_HOUR;
	
	/**
	 * The possible names of the environment variable representing the Maven installation folder.
	 */
	private static final List<String> MAVEN_HOME_ENV_VAR_NAMES = asList("MAVEN_HOME", "M2_HOME");
	
	/**
	 * The {@link AppContext application context}. This is not a param.
	 */
  @EqualsAndHashCode.Exclude
  @ToString.Exclude
	@Getter
	protected final @NotNull AppContext appContext;
	
	/**
	 * Mandatory : The filesystem path to the <i>Build List file</i>.
	 */
	@Getter
	@NotNull ParamMono<Object, String> buildListFilepath;
	
	/**
	 * Optional : The filesystem path to the Maven installation folder (not the Maven repository folder).<br><br>
	 *
	 * Default  : The value of environment variable {@code MAVEN_HOME}.
	 */
	@Getter
	@NotNull ParamMono<Object, String> mavenFolder;
  
  /**
   * Optional : The filesystem path to the Maven repository folder (not the Maven installation folder).<br><br>
   *
   * Default  : [user home]\.m2\repository
   *            E.g. {@code C:\Users\Davide\.m2\repository}.
   */
  @Getter
  @NotNull ParamMono<Object, String> mavenRepoFolder;
	
	/**
	 * Optional: The timeout of issuing a build command.
	 */
	@Getter
	ParamMono<Object, Long> commandTimeoutMs;
  
  /**
   * Optional: Whether or not the output generated by the build commands invoked by the Orchestrator must be captured
   *           (in order to log it). If yes, the captured text can still be also presented to the user, by setting the
   *           parameter {@link #showCapturedOutput} to {@code true}.
   */
  @Getter
  @NotNull ParamMono<Object, Boolean> captureBuildOutput;
  
  /**
   * Optional: Whether or not, when {@link #captureBuildOutput} is {@code true}, that captured output generated by the
   *           build commands must also still be shown to the user. This parameter can be true only if {@link
   *           #captureBuildOutput} is {@code true}.
   */
  @Getter
  @NotNull ParamMono<Object, Boolean> showCapturedOutput;
	
	
	/**
	 * Non-public constructor.
	 *
	 * @param configurationMap {@link #configurationMap}.
	 * @param sourceDescr      {@link #sourceDescr}.
	 */
	BuildOrchestratorParams(Map<String, String> configurationMap, String sourceDescr, @NotNull AppContext appContext) {
		
		super(configurationMap, null, sourceDescr, appContext.userLog);
		
		this.appContext = appContext;
	}
	
	
	/**
	 * Sets new instances of all the params into this {@link BuildOrchestratorParams}.
	 */
	public void addAllParams() {
		
		// Param BuildListFilePath :
		
		this.buildListFilepath = new ParamMono<>(this, "BuildListFile");
    
    // Param MavenFolder :
    
    this.mavenFolder = new ParamMono<>(this, "MavenFolder");
    
    // Param MavenRepoFolder :
    
    this.mavenRepoFolder = new ParamMono<>(this, "MavenRepoFolder");
		
		// Param CommandTimeoutMs :
		
		this.commandTimeoutMs  = new ParamMono<>(this, "CommandTimeoutMs");
    
    // Param CaptureBuildOutput :
    
    this.captureBuildOutput = new ParamMono<>(this, "CaptureBuildOutput");
    
    // Param ShowCapturedOutput :
    
    this.showCapturedOutput =  new ParamMono<>(this, "ShowCapturedOutput");
  }
	
	@Override
	public void populate() {
		
		// Param BuildListFilePath :
		
		this.buildListFilepath.setValueParser(new NeutralStringParser()).loadOptionalValue(null);
		
		// Param MavenFolder :
		
		final String mvnHomeEnvVarName = MAVEN_HOME_ENV_VAR_NAMES.stream()
	                                                  .filter(n -> isNotBlank(System.getenv(n)))
		                                                .findFirst().orElse("Maven");
		
		this.mavenFolder.setValueParser(new NeutralStringParser()).loadOptionalValue(
														defaultIfBlank(System.getenv(mvnHomeEnvVarName)
																										, SEPARATOR_CHAR + "Maven"));
    
    // Param MavenRepoFolder :
    
    this.mavenRepoFolder.setValueParser(new NeutralStringParser()).loadOptionalValue(calcPath(
                                defaultIfBlank(System.getProperty("user.home"), EMPTY)
                                          , ".m2", "repository"));
		// Param CommandTimeoutMs :
		
		this.commandTimeoutMs.setValueParser(new LongStringParser()).loadOptionalValue(
																																 L(DEFAULT_COMMAND_TIMEOUT_MS));
    // Param CaptureBuildOutput :
    
    this.captureBuildOutput.setValueParser(new BooleanStringParser()).loadOptionalValue(FALSE);
    
    // Param ShowCapturedOutput :
    
    this.showCapturedOutput.setValueParser(new BooleanStringParser()).loadOptionalValue(FALSE);
	}
	
	@Override
	public void validate() {
		
		// Param BuildListFilePath :
		
		validateExistingFilePathParam(this.buildListFilepath);
    
    // Param MavenFolder :
    
    validateExistingFolderPathParam(this.mavenFolder);
    
    // Param MavenRepoFolder :
    
    validateExistingFolderPathParam(this.mavenRepoFolder);
		
		// Param CommandTimeoutMs :
		
		final Long timeout = this.commandTimeoutMs.value;
		
		handleParamValidationResult(this.commandTimeoutMs.name, timeout
										 , timeout == null || timeout.longValue() >= ZERO_l
									, "A non-negative number of milliseconds", this.sourceDescr);
    
    // Param CaptureBuildOutput :
    
    Boolean booleanValue = this.captureBuildOutput.value;
    
    handleParamValidationResult(this.captureBuildOutput.name, booleanValue
                     , booleanValue == TRUE || this.showCapturedOutput.value == FALSE
                  , "true otherwise " + this.showCapturedOutput.name + " must be false"
                , this.sourceDescr);
    
    // Param ShowCapturedOutput :
    
    booleanValue = this.showCapturedOutput.value;
    
    handleParamValidationResult(this.showCapturedOutput.name, booleanValue
                     , booleanValue == FALSE || this.captureBuildOutput.value == TRUE
                  , "false otherwise " + this.captureBuildOutput.name + " must be true"
                , this.sourceDescr);
  }
	
	/**
	 * Returns a new {@link EmptyValueChangeTextReader} because {@link BuildOrchestrator} doesn't use the PVDC
	 * functionality (<b>PVDC</b> = <i>Parameter Value Dynamic Change</i>).
	 * 
	 * @see AParams#getDefaultValueChangeReader()
	 */
	@Override
	protected AValueChangeTextReader<Object, ?> getDefaultValueChangeReader() {
		
		return new EmptyValueChangeTextReader<>(this.log);
	}

}
