/**
 * Created by Davide on 2026-01-28 .
 *
 * @formatter:off
 */

package build_orchestrator;

import application.AAppContext;
import dfile.value_parser.FilesystemPathParser;
import dparam.AParams;
import dparam.ParamMono;
import dparam.ParamMulti;
import dparam.pvdc.AValueChangeInfo;
import dparam.pvdc.change_loader.AValueChangeTextReader;
import dparam.pvdc.change_loader.EmptyValueChangeTextReader;
import dutil.string.value_parser.BooleanStringParser;
import dutil.string.value_parser.LongStringParser;
import dutil.string.value_parser.NeutralStringParser;
import dutil.value_holder.ObjectAndDescr;
import dutil.value_holder.TwoObjects;
import jakarta.validation.constraints.NotNull;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

import java.io.File;
import java.io.Serial;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static dfile.file.FileUtilities.calcPath;
import static dmaven.MavenUtilities.findMavenHome;
import static dutil.date.DateTimeUtilities.MS_IN_HOUR;
import static dutil.list.text.TextListUtilities.listToString;
import static dutil.number.NumberUtilities.L;
import static dutil.number.NumberUtilities.ONE_i;
import static dutil.number.NumberUtilities.ZERO_l;
import static dutil.string.TextUtilities.NL;
import static dutil.string.TextUtilities.NLT;
import static dutil.string.TextUtilities.dqStr;
import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import static org.apache.commons.lang3.StringUtils.EMPTY;
import static org.apache.commons.lang3.StringUtils.defaultIfBlank;

/**
 * Class containing the fields that represent the user-controlled parameters (AKA "inputs") of a {@link
 * BuildOrchestrator} executable instance.<br><br>
 * The {@link AValueChangeInfo#marker Value Change Marker}s are of unspecified type because {@link BuildOrchestrator}
 * doesn't use the PVDC functionality (<b>PVDC</b> = <i>Parameter Value Dynamic Change</i>).
 */
@ToString(callSuper = true)
public class BuildOrchestratorParams extends AParams<Object> {
	
	
	@Serial
	private static final long serialVersionUID = -4623955895467891834L;
	
	/**
	 * Default for optional param {@link #commandTimeoutMs}, 1 h (3,600,000 ms).
	 */
	private static final long DEFAULT_COMMAND_TIMEOUT_MS = MS_IN_HOUR;
	
	/**
	 * The {@link AAppContext application context}. This is not a param.
	 */
  @EqualsAndHashCode.Exclude
  @ToString.Exclude
	@Getter
	protected final @NotNull AAppContext appContext;
	
	/**
	 * Mandatory : The filesystem path to the <i>Build List file</i>.
	 */
	@Getter
  ParamMono<Object, String> buildListFilepath;
	
	/**
	 * Optional : The filesystem path to the Maven installation folder (not the Maven repository folder).<br><br>
	 *
	 * Default  : The value of environment variable {@code MAVEN_HOME}.
	 */
	@Getter
  ParamMono<Object, String> mavenFolder;
  
  /**
   * Optional : The filesystem path to the Maven repository folder (not the Maven installation folder).<br><br>
   *
   * Default  : [user home]\.m2\repository
   *            E.g. {@code C:\Users\Davide\.m2\repository}.
   */
  @Getter
  ParamMono<Object, String> mavenRepoFolder;
	
	/**
	 * Optional: The timeout of issuing a build command.
	 */
	@Getter
  ParamMono<Object, Long> commandTimeoutMs;
  
  /**
   * Optional: Whether or not the output generated by the build commands invoked by the Orchestrator must be captured
   *           (in order to log it). If yes, the captured text can still be also presented to the user, by setting the
   *           parameter {@link #showCapturedOutput} to {@code true}.
   */
  @Getter
  ParamMono<Object, Boolean> captureBuildOutput;
  
  /**
   * Optional: Whether or not, when {@link #captureBuildOutput} is {@code true}, that captured output generated by the
   *           build commands must also still be shown to the user. This parameter can be true only if {@link
   *           #captureBuildOutput} is {@code true}.
   */
  @Getter
  ParamMono<Object, Boolean> showCapturedOutput;
  
  /**
   * Optional: Whether or not, instead of directly executing the OS commands from
   *           the Build List, for each command a temporary .BAT script is created
   *           containing one line per each element of this multiple parameter,
   *           followed by the OS command to execute, then this script is executed
   *           and deleted.
   *           This can be used to run preliminary OS commands that make changes
   *           to the shell environment whose effect must be preserved when the
   *           final OS command runs.
   *
   *           For example, if the command to run is
   *
   *           mvn clean install
   *
   *           and it's desired to change the console's codepage to one that the
   *           OS command will use (65001 in this example, which corresponds to
   *           UTF-8), this parameter can be set to a 2-element list like:<br><br>
   *
   *           ECHO OFF<br>
   *           CHCP 65001 >NUL<br><br>
   *
   *           If the OS is not Windows, an exception is thrown if this parameter
   *           is given. This is to force the caller to check whether the OS is
   *           Windows or not, because if it's not then the content of this
   *           parameter will be ignored which might be unexpected.
   */
  @Getter
  ParamMulti<Object, String> runInScriptIfWin;
	
	
	/**
	 * Non-public constructor.
	 *
	 * @param configurationMap {@link #configurationMap}.
	 * @param sourceDescr      {@link #sourceDescr}.
	 */
	BuildOrchestratorParams(@NotNull Map<String, String> configurationMap, String sourceDescr, @NotNull AAppContext appContext) {
		
		super(configurationMap, null, sourceDescr, appContext.userLog);
		
		this.appContext = appContext;
	}
	
	
	/**
	 * Sets new instances of all the params into this {@link BuildOrchestratorParams}.
	 */
	public void addAllParams() {
		
		// Param BuildListFilePath :
		
		this.buildListFilepath = new ParamMono<>(this, "BuildListFile");
    
    // Param MavenFolder :
    
    this.mavenFolder = new ParamMono<>(this, "MavenFolder");
    
    // Param MavenRepoFolder :
    
    this.mavenRepoFolder = new ParamMono<>(this, "MavenRepoFolder");
		
		// Param CommandTimeoutMs :
		
		this.commandTimeoutMs  = new ParamMono<>(this, "CommandTimeoutMs");
    
    // Param CaptureBuildOutput :
    
    this.captureBuildOutput = new ParamMono<>(this, "CaptureBuildOutput");
    
    // Param ShowCapturedOutput :
    
    this.showCapturedOutput =  new ParamMono<>(this, "ShowCapturedOutput");
    
    // Param RunInScriptIfWin :
    
    this.runInScriptIfWin = new ParamMulti<>(this, "RunInScriptIfWin", ONE_i);
  }
	
	@Override
	public void populate() {
		
		// Param BuildListFilePath :
		
		this.buildListFilepath.setValueParser(new FilesystemPathParser()).loadOptionalValue(null);
		
		// Param MavenFolder :
		
  
  
//		@@@@@@@ final String mvnHomeEnvVarName = MAVEN_HOME_ENV_VAR_NAMES.stream()
//	                                                  .filter(n -> isNotBlank(System.getenv(n)))
//		                                                .findFirst().orElse("Maven");

    final TwoObjects<ObjectAndDescr<Path>, List<ObjectAndDescr<String>>> mvnHomeDiscovery = findMavenHome(
                                                                                                     this.appContext);
    
    this.appContext.outUserLog("Maven home Discovery : found : " + dqStr(mvnHomeDiscovery.o1) + NL + "Checked and discarded :" + NLT + listToString(mvnHomeDiscovery.o2, EMPTY, EMPTY, EMPTY, NLT));
    
		this.mavenFolder.setValueParser(new FilesystemPathParser()).loadOptionalValue(
                                                                 mvnHomeDiscovery.o1 != null    ?
                                                                                  mvnHomeDiscovery.o1.toString() :
                                                                                  File.separator + "Maven");
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Param MavenRepoFolder :
    
    this.mavenRepoFolder.setValueParser(new FilesystemPathParser()).loadOptionalValue(calcPath(
                                defaultIfBlank(System.getProperty("user.home"), EMPTY)
                                          , ".m2", "repository"));
		// Param CommandTimeoutMs :
		
		this.commandTimeoutMs.setValueParser(new LongStringParser()).loadOptionalValue(
																																 L(DEFAULT_COMMAND_TIMEOUT_MS));
    // Param CaptureBuildOutput :
    
    this.captureBuildOutput.setValueParser(new BooleanStringParser()).loadOptionalValue(FALSE);
    
    // Param ShowCapturedOutput :
    
    this.showCapturedOutput.setValueParser(new BooleanStringParser()).loadOptionalValue(FALSE);
    
    // Param RunInScriptIfWin :
    
    this.runInScriptIfWin.setValueParser(new NeutralStringParser()).loadOptionalValues(null);
  }
	
	@Override
	public void validate() {
		
		// Param BuildListFilePath :
		
		validateExistingFilePathParam(this.buildListFilepath);
    
    // Param MavenFolder :
    
    validateExistingFolderPathParam(this.mavenFolder);
    
    // Param MavenRepoFolder :
    
    validateExistingFolderPathParam(this.mavenRepoFolder);
		
		// Param CommandTimeoutMs :
		
		final Long timeout = this.commandTimeoutMs.value;
		
		handleParamValidationResult(this.commandTimeoutMs.name, timeout
										 , timeout == null || timeout.longValue() >= ZERO_l
									, "A non-negative number of milliseconds", this.sourceDescr);
    
    // Param CaptureBuildOutput :
    
    Boolean booleanValue = this.captureBuildOutput.value;
    
    handleParamValidationResult(this.captureBuildOutput.name, booleanValue
                     , booleanValue == TRUE || this.showCapturedOutput.value == FALSE
                  , "true otherwise " + this.showCapturedOutput.name + " must be false"
                , this.sourceDescr);
    
    // Param ShowCapturedOutput :
    
    booleanValue = this.showCapturedOutput.value;
    
    handleParamValidationResult(this.showCapturedOutput.name, booleanValue
                     , booleanValue == FALSE || this.captureBuildOutput.value == TRUE
                  , "false otherwise " + this.captureBuildOutput.name + " must be true"
                , this.sourceDescr);
    
    // Param RunInScriptIfWin :
    
    /** Already validated at loading time, see {@link ParamMulti#validateCounters()} . */
  }
	
	/**
	 * Returns a new {@link EmptyValueChangeTextReader} because {@link BuildOrchestrator} doesn't use the PVDC
	 * functionality (<b>PVDC</b> = <i>Parameter Value Dynamic Change</i>).
	 * 
	 * @see AParams#getDefaultValueChangeReader()
	 */
	@Override
	protected AValueChangeTextReader<Object, ?> getDefaultValueChangeReader() {
		
		return new EmptyValueChangeTextReader<>(this.log);
	}

}
